config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :categories
  resources :users, only: [:show, :create, :edit, :update]


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :creator, foreign_key: "user_id", class_name: "User"
  belongs_to :post

  has_many :votes, as: :voteable


  validates :body, presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user

  def create

    @the_post = Post.find_by(slug: params[:post_id])
    @comment = @the_post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user 

    if @comment.save
      flash[:notice] = 'Your comment was added'
      redirect_to post_path(@the_post)
    else
      render 'posts/show'
    end
  end

  def vote
    @comment = Comment.find(params[:id])
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: @comment)
    
    respond_to do |format|
      format.html do
        if @vote.valid?
          if @vote.vote == true
            flash[:notice] = 'Thanks for your vote'
          else
            flash[:notice] = 'OH DEAR! but thanks'
          end
        else
          flash[:error] = 'You can only vote once for this comment'
        end
        redirect_to :back
      end
      format.js
    end

  end
end

app/views/comments/_comments.html.erb
<% show_post_title ||= false %>
<div class="row">
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %>
    <br />
    <span id="comment_<%= comment.id %>_votes"><%= "#{comment.total_votes} #{'vote'.pluralize(comment.total_votes)}" %></span>
    <br />
    <% if logged_in? %>
      <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div  class="well span8">
    <em><%= comment.body %></em>
    <% if show_post_title %>
     on <%= link_to comment.post.title, post_path(comment.post) %>
     <% end %>
    <br />
    <span class="quiet">Comment by: </span><%= link_to comment.creator.username, user_path(comment.creator) %>
    <small> <%= time_ago(comment.created_at) %> ago</small>
  </div>
</div>

app/views/comments/vote.js.erb
<% if @vote.valid? %>
  $('#comment_<%= @comment.id %>_votes').html('<%= pluralize(@comment.total_votes, 'vote') %>')
<% else %>
  alert('You have already voted on tis comment')
<% end %>