config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :categories
  resources :users, only: [:show, :create, :edit, :update]


end

app/models/post.rb
class Post < ActiveRecord::Base
  include Voteable

  belongs_to :creator, foreign_key: "user_id", class_name: "User"
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable

  validates :title, presence: true
  validates :url, presence: true
  validates :description, presence: true

  before_save :generate_slug!

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.title)
    post = Post.find_by(slug: the_slug)
    count = 2
    while post && post != self
      the_slug = append_suffix(the_slug, count)
      post = Post.find_by(slug: the_slug)
      count += 1
    end
    self.slug = the_slug.downcase
  end

  def append_suffix(str,count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + "-#{count}"
    else
      return str + "-#{count}"
    end
  end

  def to_slug(name)
    str = name.strip
    str.gsub!(/\s*[^A-Za-z0-9]\s*/, '-')
    str.gsub!(/-+/,"-")
    str.chop! if str.last == '-'
    str.downcase
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]


  def index
    @posts = Post.all.sort_by{|the_post| the_post.total_votes}.reverse
  end

  def show
    @comment= Comment.new
  end

  def new
    @the_post = Post.new
  end

  def create
    @the_post = Post.new(post_params)
    @the_post.creator = current_user



    if @the_post.save
      flash[:notice] = "Your post was created."
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def vote
    @vote = Vote.create(voteable: @the_post, creator: current_user, vote: params[:vote])

    respond_to do |format| 
      format.html do 
        if @vote.valid?
          if @vote.vote == true
            flash[:notice] = 'Thanks for voting'
          else
            flash[:notice] = 'OUCH! but thanks for voting'
          end
        else
          flash[:error] = 'You can only vote for this once'
        end
        redirect_to :back
      end
      format.js
    end

  end

  def edit; end

  def update
    if @the_post.update(post_params)
      flash[:notice] = "The post was updated"
      redirect_to post_path
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end

  def set_post
    @the_post = Post.find_by(slug: params[:id])
  end
end

app/views/posts/_form.html.erb
<%= render 'shared/errors', the_object: @the_post %>

<div class="well">
  <%= form_for @the_post do |f| %>
    <div class="control-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
    </div>
    <div class="control-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="control-group">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5 %>
    </div>

    <div class="control-group">
      <%= f.label :Categories %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: "checkbox inline"){cb.check_box(class: "checkbox") + cb.text} %>
      <% end %>
    </div>
<!-- 
    <select name='options[]' multiple='multiple'>
      <% Category.all.each do |cat| %>
        <option value="<%= cat.id %>"><%= cat.name %></option>
      <% end %>
    </select> -->




    <br />
      <%= f.submit(@the_post.new_record? ? "Create Post" : "Update Post", class: 'btn btn-primary btn-small') %>
  <% end %>
</div>

app/views/posts/_post.html.erb
<div class="row">  
  <div class="span0 well text-center">
    <% if logged_in? %>
      <%= link_to vote_post_path(the_post, vote: true), method: 'post', remote: true do %>
        <i class="icon-arrow-up"></i>
      <% end %>
    <% end %> 
    <br />
      <span id='post_<%= the_post.slug %>_votes'><%= "#{the_post.total_votes} #{'vote'.pluralize(the_post.total_votes)}" %></span>
    <br />
    <% if logged_in? %>
      <%= link_to vote_post_path(the_post, vote: false), method: 'post', remote: true do %>
        <i class="icon-arrow-down"></i>
      <% end %>
    <% end %>
  </div>
  <div class="span8 well">
    <%= render the_post.categories %>
    <h4><%= link_to the_post.title, post_path(the_post) %></h4>
    <a href="<%= url_fixer(the_post.url) %>"><%= the_post.url %></a>
    <p><%= the_post.description %></p>
    <p><span class="quiet">posted by</span> <%= the_post.creator.username %> <small><%= time_ago(the_post.created_at) %> ago</small></p>
    <p>Comments: <%= link_to(the_post.comments.size, post_path(the_post)) %></p>
    
    <% if current_user == the_post.creator %>  
      <p>(<%= link_to 'edit', edit_post_path(the_post) %>)</p>
    <% end %>

  </div>
</div>

app/views/posts/edit.html.erb
<%= render 'shared/content_title', title: 'Edit post' %>


<div class="well">
  <%= render 'form' %>
</div>

app/views/posts/index.html.erb
<%= render "shared/content_title", title: "All Posts" %>


  <% @posts.each do |the_post| %>
    <%= render 'post', the_post: the_post %>
  <% end %>

app/views/posts/new.html.erb
<%= render 'shared/content_title', title: 'Create new post' %>


<%= render 'form' %>

app/views/posts/show.html.erb
<% if current_user == @the_post.creator %>
  <p class="pull-right">
    [<%= link_to 'edit this post', edit_post_path(@the_post.slug) %>]
  </p>
<% end %>

<%= render "shared/content_title", title: @the_post.title %>

<div class="control-group">
  <p>
    <%= render @the_post.categories %>
  </p> 
  <p><%= @the_post.description %></p>
  <p><%= @the_post.creator.username %></p>
  <a href="<%= @the_post.url %>"><%= @the_post.url %></a>
</div>
<% if logged_in? %>
  <%= form_for [@the_post, @comment] do |f| %>
    <%= render 'shared/errors', the_object: @comment %>
    <div class="control-group">
      <%= f.label :body, 'Leave a comment' %>
      <%= f.text_area :body, rows: 5, class: 'span4' %>
    </div> 
    
    <%= f.submit 'Add comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>
<% @the_post.reload.comments.each do |comment| %>
  <%= render 'comments/comments', comment: comment %>
<% end %>

app/views/posts/vote.js.erb
<% if @vote.valid? %>
  $('#post_<%=@the_post.slug%>_votes').html('<%= pluralize(@the_post.total_votes, 'vote') %>')
<% else %>
  alert('You can only vote once')
<% end %>