config/routes.rb
PostitTemplate::Application.routes.draw do
  root to: 'posts#index'

  get 'register', to: 'users#new'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'




  resources :posts, except: [:destroy] do 
    member do
      post :vote
    end

    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :categories
  resources :users, only: [:show, :create, :edit, :update]


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :post_categories
  has_many :posts, through: :post_categories

  validates :name, presence: true
  validates :name, uniqueness: { case_sensitive: false }

  before_save :generate_slug!

  def to_param
    self.slug
  end

  def generate_slug!
    the_slug = to_slug(self.name)
    cat = Category.find_by(slug: the_slug)
    count = 2
    while cat && cat != self
      the_slug = append_suffix(the_slug, count)
      cat = Category.find_by(slug: the_slug)
      count += 1
    end
    self.slug = the_slug.downcase
  end

  def append_suffix(str,count)
    if str.split('-').last.to_i != 0
      return str.split('-').slice(0...-1).join('-') + "-#{count}"
    else
      return str + "-#{count}"
    end
  end

  def to_slug(name)
    str = name.strip
    str.gsub!(/\s*[^A-Za-z0-9]\s*/, '-')
    str.gsub!(/-+/,"-")
    str.chop! if str.last == '-'
    str.downcase
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def index
  end

  def new
    @the_category = Category.new
  end

  def create
    @the_category = Category.new(category_params)

    if @the_category.save
      flash[:notice] = "Your category was added"
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @the_category = Category.find_by(slug: params[:id])
  end


  private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/views/categories/_category.html.erb
<span class="badge"><%= link_to category.name, category_path(category) %></span>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: "Posts by category" %>

<ul>
  <% @categories.each do |cat| %>
    <% cat.posts.each do |post| %>
      <li><%= post.title %></li>
    <% end %>
  <% end %>
</ul>

<ul>
  <% @categories.each do |catname| %>
    <li><%= catname.name %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'Add new category' %>

<%= render 'shared/errors', the_object: @the_category %>

<div class="well">
  <%= form_for @the_category do |f| %>
    <div class="control-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
      <%= f.submit(@the_category.new_record? ? "Add Category" : "Update Category", class: 'btn btn-primary btn-small') %>
  <% end %>
</div>

app/views/categories/show.html.erb
<% header = link_to('All Posts', posts_path) + "&raquo; #{@the_category.name}".html_safe %>
<%= render 'shared/content_title', title: header  %>

  <% @the_category.posts.each do |the_post| %>
    <%= render 'posts/post', the_post: the_post %>
  <% end %>